spring:
  application:
    name: blog

  datasource:
    url: jdbc:mysql://localhost:3306/blogdb  # 로컬에 떠있는 MySQL 컨테이너/인스턴스
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: geo        # 로컬 MySQL
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true